//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Animal
{
	private Categoria categoria
	{
		get;
		set;
	}

	private bool vivo
	{
		get;
		set;
	}

	private string nombre
	{
		get;
		set;
	}

	private string registro
	{
		get;
		set;
	}

	private int gen
	{
		get;
		set;
	}

	private string reg_trazab
	{
		get;
		set;
	}

	private Char sexo
	{
		get;
		set;
	}

	private Date fecha_nacim
	{
		get;
		set;
	}

	private Animal reg_padre
	{
		get;
		set;
	}

	private Animal reg_madre
	{
		get;
		set;
	}

	private string origen
	{
		get;
		set;
	}

	private string identificacion
	{
		get;
		set;
	}

	private List<String> imagenes
	{
		get;
		set;
	}

	private List<Evento> eventos
	{
		get;
		set;
	}

	public virtual Categoria Categoria
	{
		get;
		set;
	}

	public virtual IEnumerable<Evento> Evento
	{
		get;
		set;
	}

}

