//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Categoria
{
	protected virtual int id_categ
	{
		get;
		set;
	}

	protected virtual string observacion
	{
		get;
		set;
	}

	protected virtual string nombre
	{
		get;
		set;
	}

}

