//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum Categorias_concurso
{
	Vaquillona_Intermedia = 1,
	Hembra_Junior = 2,
	Hembra_SH = 3,
	Ternero_Menor = 4,
	Vaquillona_Mayor = 5,
	Vaca_3_años_Senior = 6,
	Ternera_Menor = 7,
	Vaca_2_años_Junior = 8,
	Vaca_2_años_Senior = 9,
	Vaca_4_años = 10,
	Vitalicia_SH = 11,
	Vaca_Intermedia = 12,
	Pedigree = 13,
	Ternera_Mayor = 14,
	Suprema  = 15,
	Vaca_3_años_Junior = 16,
	Vaca_Adulta = 17,
	Mejor_Ubre_Adulta_SH = 18,
	Vitalicia = 19,
	Mejor_criador_y_expositor_SH = 20,
	Vaca_Joven_Mayor = 21,
	Mejor_Ubre_Categoría = 22,
	Cuarto_Premio = 23,
	General = 24,
	Vaca_2_años = 25,
	Vaquillona_Menor = 26,
	Ternera = 27,
	Ternera_Juvenil = 28,
	Produccion = 29,

}
