//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Consurso : Evento
{
	private int anio
	{
		get;
		set;
	}

	private List<Premio> premios
	{
		get;
		set;
	}

	public virtual IEnumerable<Premio> Premio
	{
		get;
		set;
	}

}

