//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Control_Producc : Evento
{
	private Float grasa
	{
		get;
		set;
	}

	private Float leche
	{
		get;
		set;
	}

	private int dias_para_control
	{
		get;
		set;
	}

}

