//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Empleado
{
	private bool activo
	{
		get;
		set;
	}

	private int id_empleado
	{
		get;
		set;
	}

	private string nombre
	{
		get;
		set;
	}

	private string apellido
	{
		get;
		set;
	}

}

