//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum Enfermedades
{
    MASTITIS = 1,
    METRITIS,
    RETENCION_DE_PLACENTA,
    PROLAPSO,
    CARBUNCO,
    MANCHA,
    GANGRENA,
    NEUMOENTERITIS,
    DIGESTIVAS,
    RETICULITIS,
    INTOXICACIONES,
    METEORISMO,
    SINDROME_DE_VACA_CAIDA,
    HIPOCALCEMIA,
    MUERTE_DESCONOCIDA,
    CESAREA,
    COJERAS,
    PARASITOSIS,
    PARALISIS_POSTERIOR,
    LEUCOCIS,
    ACCIDENTALES,
    CUERPO_EXTRANO,
    DIARREA_VIRAL_BOVINA,
    ACIDOSIS,
    INDIGESTIONES,
    RETICULITIS_2,
    ALCALOSIS,
    SEPTICEMIA_GENERALIZADA,
    MUERTE_X_RAYO,
    DESCARGA_ELECT_X_RAYO,
    NEUMONIA_CRONICA,
    PARALISIS_POST_PARTO,
    CLOSTRIDIOSIS,
    POLIARTRITIS,
    ENFRI_TEMPORALES,
    HIPOMAGNESEMIA,
    TORSION_DE_ABOMASO,
    PERITONITIS,
    MAL_CALOSTRAMIENTO,
    ENTERITIS,
    GOLPE_DE_CALOR,
    POLIARTROSIS_GENERALIZADA,
    RETICULITIS_TRAUMATI,
    PERICARDITIS_TRAUMAT,
    MUERTE_EN_EL_PARTO,
    TOXEMIA_PRENEZ_MELLI,
    DEFECTOS_CONGENITOS,
    DESMEJORAMIENTO_GRAL,
    ABSCESO_ILEOHEPATICO,
    COCCIDIOCIS,
    SALMONELOSIS,
    SEPTI_GDA_POST_PARTO,
    MUERTE_NATURAL,
    ROT_UTERINA_POST_PARTO,
    PARAL_RUMINAL_NERVIO,
    FOTOSENSIBILIDAD,
    INFARTO,
    E_COLI,
    MUERTE_SUBITA,


}
