//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Evento
{
	protected virtual Date fecha
	{
		get;
		set;
	}

	protected virtual int id_evento
	{
		get;
		set;
	}

	protected virtual string comentarios
	{
		get;
		set;
	}

}

