//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Parto : Evento
{
	private int id_parto
	{
		get;
		set;
	}

	private Date fecha_serv
	{
		get;
		set;
	}

	private string observaciones
	{
		get;
		set;
	}

	private Char sexo_parto
	{
		get;
		set;
	}

	private string reg_hijo
	{
		get;
		set;
	}

}

