//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Premio
{
	private string nombre_premio
	{
		get;
		set;
	}

	public virtual Categorias_concurso categ_concuros
	{
		get;
		set;
	}

}

