//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Remito
{
	private Date fecha
	{
		get;
		set;
	}

	private Empresas empresa
	{
		get;
		set;
	}

	private string factura
	{
		get;
		set;
	}

	private string matricula
	{
		get;
		set;
	}

	private Float litros
	{
		get;
		set;
	}

	private string observaciones
	{
		get;
		set;
	}

	private string encargado
	{
		get;
		set;
	}

	private Float temp_1
	{
		get;
		set;
	}

	private Float temp_2
	{
		get;
		set;
	}

}

