//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Servicio : Evento
{
	private bool serv_monta_natural
	{
		get;
		set;
	}

	private Animal reg_padre
	{
		get;
		set;
	}

	private Empleado inseminador
	{
		get;
		set;
	}

	public virtual Animal Animal
	{
		get;
		set;
	}

	public virtual Empleado Empleado
	{
		get;
		set;
	}

}

