//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Usuario
{
	private string nickname
	{
		get;
		set;
	}

	private string password
	{
		get;
		set;
	}

	private string nombre
	{
		get;
		set;
	}

	private string apellido
	{
		get;
		set;
	}

	private string email
	{
		get;
		set;
	}

}

