//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Aborto : Evento
    {
        public Aborto()
        {
        }

        public Aborto(Animal regPadre)
        {
            Reg_padre = regPadre;
        }

        public Animal Reg_padre { get;set; }

    }
}

