//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Aborto : Evento
    {
        public Aborto()
        {
        }

        public Aborto(string regPadre)
        {
            Reg_padre = regPadre;
        }

        public string Reg_padre { get;set; }

        public override string ToString()
        {
            return "Registro Padre: " + Reg_padre + ", " + Comentarios;
        }

    }
}

