//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Baja : Evento
    {
        public Baja()
        {
            Nombre = "Baja";
        }

        public Baja(Enfermedad enfermedad)
        {
            Enfermedad = enfermedad;
        }

        public virtual short Tipo { get; set; }

        public Enfermedad Enfermedad { get; set; }

        public string Codigo { get; set; }

        public override string ToString()
        {
            string enfStr = "";
            if (Id_evento == 11) Nombre = "Venta";
            else if (Id_evento == 12) Nombre = "Muerte";
            if (Enfermedad != null) enfStr = ". " + Enfermedad.ToString();
            return Nombre + enfStr;
        }

    }
}

