//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Calificacion : Evento
    {
        public Calificacion()
        {
            Nombre = "Calificación";
        }

        public Calificacion(int puntos, string letras)
        {
            Puntos = puntos;
            Letras = letras;
        }

        public string Letras { get; set; }

        public int Puntos { get; set; }

        public override string ToString()
        {
            return Letras + " " + Puntos.ToString(); 
        }

    }
}

