//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Calificacion : Evento
{
    public Calificacion()
    {
    }

    public Calificacion(int puntos, string letras)
    {
        Puntos = puntos;
        Letras = letras;
    }

    public string Letras { get; set; }

    public int Puntos { get; set; }

}

