//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Categoria
    {
        public Categoria()
        {
        }

        public Categoria(string nombre, string observacion, int idCateg)
        {
            Nombre = nombre;
            Observacion = observacion;
            Id_categ = idCateg;
        }

        public int Id_categ { get; set; }

        public string Observacion { get; set; }

        public string Nombre { get; set; }

        public override string ToString()
        {
            return Id_categ.ToString() + " - " + Nombre;
        }

    }
}

