//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class CategoriaConcurso
    {
        public CategoriaConcurso()
        {
        }

        public CategoriaConcurso(string nombre)
        {
            Nombre = nombre;
        }

        public CategoriaConcurso(string nombre, int idCateg)
        {
            Nombre = nombre;
            Id_categ = idCateg;
        }

        public int Id_categ { get; set; }

        public string Nombre { get; set; }

        public override string ToString()
        {
            return Nombre;
        }

    }
}

