//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public abstract class Categoria
    {
        public Categoria()
        {
        }

        protected Categoria(string nombre, string observacion, int idCateg)
        {
            Nombre = nombre;
            Observacion = observacion;
            Id_categ = idCateg;
        }

        protected virtual int Id_categ { get; set; }

        protected virtual string Observacion { get; set; }

        protected virtual string Nombre { get; set; }

    }
}

