//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Celo_Sin_Servicio : Evento
    {
        public Celo_Sin_Servicio()
        {
            Nombre = "Celos sin servicio";
        }

        public override string ToString()
        {
            return Nombre;
        }

    }
}

