//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Cmt : Evento
    {
        public Cmt()
        {
            Nombre = "Diagnóstico C.M.T.";
        }

        public override string ToString()
        {
            return Nombre;
        }

    }
}

