//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Entidades
{
    public class Concurso : Evento
    {
        public Concurso()
        {
            Nombre = "Concurso";
        }

        public Concurso(List<Premio> premios, int anio, Lugar_Concurso lugar)
        {
            Premios = premios;
            Anio = anio;
            Lugar = lugar;
        }

        public int Anio { get; set; }

        public List<Premio> Premios { get; set; }

        public Lugar_Concurso Lugar { get; set; }
        
        public override string ToString()
        {
            return "Exposición: " + Lugar.ToString() + " Año: " + Anio.ToString();
        }

        //public virtual IEnumerable<Premio> Premio { get; set; }
        
    }
}

