//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Entidades
{
    public class Concurso : Evento
    {
        public Concurso()
        {
            Nombre = "Concurso";
        }

        public Concurso(LugarConcurso lugar, Premio elPremio)
        {
            ElPremio = elPremio;
            Lugar = lugar;
        }

        public Premio ElPremio { get; set; }

        public LugarConcurso Lugar { get; set; }
        
        public override string ToString()
        {
            string prem = "";
            if (ElPremio != null) prem = ElPremio.ToString() + ". ";
            return prem + Lugar.ToString();
        }
        
    }
}

