//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Entidades
{
    public class Concurso : Evento
    {
        public Concurso()
        {
            Nombre = "Concurso";
        }

        public Concurso(string lugar, string elPremio)
        {
            ElPremio = elPremio;
        }

        public string ElPremio { get; set; }


        public LugarConcurso NombreLugarConcurso { get; set; }


        public CategoriaConcurso Categoria { get; set; }

        public override string ToString()
        {
            string prem = "";
            if (ElPremio != null) prem = ElPremio +" "  ;
            return prem + Categoria.ToString()+". " + NombreLugarConcurso.ToString() + ".";
        }
        
    }
}

