//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Control_Total 
    {
        public Control_Total()
        {
            
        }

        public Control_Total(short vacas, double leche, double grasa, DateTime fecha)
        {
            Vacas = vacas;
            Leche = leche;
            Grasa = grasa;
            Fecha = fecha;
        }

        public double Grasa { get; set; }

        public double Leche { get; set; }

        public short Vacas { get; set; }

        public DateTime Fecha { get; set; }


    }
}

