//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Control_Producc : Evento
    {
        public Control_Producc()
        {
        }

        public Control_Producc(int diasParaControl, float leche, float grasa)
        {
            Dias_para_control = diasParaControl;
            Leche = leche;
            Grasa = grasa;
        }

        public float Grasa { get; set; }

        public float Leche { get; set; }

        public int Dias_para_control { get; set; }

    }
}

