//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Control_Producc : Evento
    {
        public Control_Producc()
        {
            Nombre = "Control de Producción";
        }

        public Control_Producc(string registro, int diasParaControl, double leche, double grasa, DateTime fecha)
        {
            Registro = registro;
            Dias_para_control = diasParaControl;
            Leche = leche;
            Grasa = grasa;
            Fecha = fecha;
        }

        public double Grasa { get; set; }

        public double Leche { get; set; }

        public int Dias_para_control { get; set; }

        public override string ToString()
        {
            return "Leche: " + Leche.ToString() + " Grasa: " + Grasa.ToString() + ". Días para control: " + Dias_para_control.ToString();
        }

    }
}

