//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Diag_Prenez : Evento
    {
        public Diag_Prenez()
        {
            Nombre = "Diagnóstico de Preñez";
        }

        public Diag_Prenez(char diagnostico)
        {
            Diagnostico = diagnostico;
        }

        public Char Diagnostico { get; set; }

        public override string ToString()
        {
            return "Diagnóstico: " + Diagnostico + ". " + Comentarios ;
        }

    }
}

