//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Diag_Prenez : Evento
{
    public Diag_Prenez()
    {
    }

    public Diag_Prenez(char diagnostico)
    {
        Diagnostico = diagnostico;
    }

    public Char Diagnostico { get; set; }

}

