//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Empleado
{
    public Empleado()
    {
    }

    public Empleado(string apellido, string nombre, int idEmpleado, bool activo)
    {
        Apellido = apellido;
        Nombre = nombre;
        Id_empleado = idEmpleado;
        Activo = activo;
    }

    public bool Activo { get; set; }

    public int Id_empleado { get; set; }

    public string Nombre { get ; set; }

    public string Apellido { get; set; }

}

