//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public enum Empresas
    {
        SCHREIBER_DULEI_SA = 0,
        CONAPROLE = 1,
        ECOLAT = 2,
    }
}
