//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Enfermedad
    {
        public Enfermedad()
        {
            Nombre = "Enfermedad";
        }

        public Enfermedad(string nomEnf)
        {
            Nombre_enfermedad = nomEnf;
        }

        public Enfermedad(int id, string nomEnf)
        {
            Nombre_enfermedad = nomEnf;
            Id = id;
        }

        public string Nombre_enfermedad { get; set; }

        public int Id { get; set; }

        public string Nombre { get; set; }

        public override string ToString()
        {
            return Nombre_enfermedad;
        }

    }
}

