//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public abstract class Evento
    {
        protected Evento()
        {
        }

        public virtual DateTime Fecha { get; set; }

        public virtual int Id_evento { get; set; }

        public virtual string Comentarios { get; set; }

        public override string ToString()
        {
            return Fecha.ToShortDateString() + " | " + Id_evento.ToString() + " | " + Comentarios;
        }

    }
}

