//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public abstract class Evento : IComparable
    {
        protected Evento()
        {
        }

        public virtual string Registro { get; set; }

        public virtual string Nombre { get; set; }

        public virtual DateTime Fecha { get; set; }

        public virtual int Id_evento { get; set; }

        public virtual string Comentarios { get; set; }

        public override string ToString()
        {
            return Fecha.ToShortDateString() + " | " + Nombre + " | " + Comentarios;
        }

        public int CompareTo(Object obj)
        {
            Evento ev = obj as Evento;
            if (ev != null)
            {
                return this.Fecha.CompareTo(ev.Fecha);
            }
            return 0;
        }

    }
}

