//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public enum Lugar_Concurso
    {
        MONTEVIDEO__Expo_Prado,
        CARDAL_Fiesta__Nacional_de_la_Leche,
        SAN_JOSE__Expo,
        TARARIRAS,
        COLONIA,
    }
}
