//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Globalization;

namespace Entidades
{
    public class LugarConcurso
    {
        public LugarConcurso()
        {
        }

        public LugarConcurso(string lugar, string nombreExpo)
        {
            Lugar = lugar;
            NombreExpo = nombreExpo;
        }

        public string Lugar { get; set; }

        public string NombreExpo { get; set; }
        
        public override string ToString()
        {
            return NombreExpo + ", " + Lugar + ".";
        }
        
    }
}

