//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public enum Motivos_Secado
    {
        LACTANCIA_COMPLETA = 1,
        RAZONES_SANITARIAS = 2,
        BAJA_PRODUCCION = 3,
        PRENEZ_AVANZADA = 4,
    }
}
