//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Muerte : Evento
    {
        public Muerte()
        {
        }

        public Muerte(Enfermedades enfermedad)
        {
            Enfermedad = enfermedad;
        }

        public Enfermedades Enfermedad { get; set; }

    }
}

