//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Muerte : Evento
    {
        public Muerte()
        {
            Nombre = "Muerte";
        }

        public Muerte(short enfermedad)
        {
            Enfermedad = enfermedad;
        }

        public short? Enfermedad { get; set; }

        public override string ToString()
        {
            return Nombre + ". " + Enfermedad.ToString();
        }

    }
}

