//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Parto : Evento
    {
        public Parto()
        {
            Nombre = "Parto";
        }

        public Parto(int idParto, DateTime fechaServ, string observaciones, char sexoParto, string regHijo)
        {
            Id_parto = idParto;
            Fecha_serv = fechaServ;
            Observaciones = observaciones;
            Sexo_parto = sexoParto;
            Reg_hijo = regHijo;
        }

        public int Id_parto { get; set; }

        public DateTime Fecha_serv { get; set; }

        public string Observaciones { get; set; }

        public Char Sexo_parto { get; set; }

        public string Reg_hijo { get; set; }

        public override string ToString()
        {
            return "Registro Hijo: " + Reg_hijo + " (" + Sexo_parto.ToString() + ") Fecha de Servicio: " + Fecha_serv.ToString() + ". Obs: " + Observaciones;
        }

    }
}

