//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Premio
    {
        public Premio()
        {
        }

        public Premio(CategoriaConcurso categConcurso, string nombrePremio)
        {
            CategConcurso = categConcurso;
            Nombre_premio = nombrePremio;
        }

        public string Nombre_premio { get; set; }

        public virtual CategoriaConcurso CategConcurso { get; set; }

        public override string ToString()
        {
            return Nombre_premio + " " + CategConcurso.ToString(); 
        } 

    }
}

