//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Premio
    {
        public Premio()
        {
        }

        public Premio(Categorias_concurso categConcuros, string nombrePremio)
        {
            Categ_concuros = categConcuros;
            Nombre_premio = nombrePremio;
        }

        public string Nombre_premio { get; set; }

        public virtual Categorias_concurso Categ_concuros { get; set; }

    }
}

