//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Remito
    {
        public Remito()
        {
        }

        public Remito(float temp2, float temp1, string encargado, string observaciones, float litros, string matricula, string factura, Empresas empresa, DateTime fecha)
        {
            temp_2 = temp2;
            temp_1 = temp1;
            Encargado = encargado;
            Observaciones = observaciones;
            Litros = litros;
            Matricula = matricula;
            Factura = factura;
            Empresa = empresa;
            Fecha = fecha;
        }

        public DateTime Fecha { get; set; }

        public Empresas Empresa { get; set; }

        public string Factura { get; set; }

        public string Matricula { get; set; }

        public float Litros { get; set; }

        public string Observaciones { get; set; }

        public string Encargado { get; set; }

        public float temp_1 { get; set; }

        public float temp_2 { get; set; }

    }
}

