//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Entidades
{
    public class Remito
    {
        public Remito()
        {
        }

        public Remito(DateTime fecha, EmpresaRemisora empresa,
                        string factura, string matricula,
                        double litros, string observaciones,
                        string encargado, double temp2, double temp1 )
        {
            Fecha = fecha;
            Empresa = empresa;
            Factura = factura;
            Matricula = matricula;
            Litros = litros;
            Observaciones = observaciones;
            Encargado = encargado;
            Temp_1 = temp1;
            Temp_2 = temp2;
        }

        public DateTime Fecha { get; set; }

        public EmpresaRemisora Empresa { get; set; }

        public string Factura { get; set; }

        public string Matricula { get; set; }

        public double Litros { get; set; }

        public string Observaciones { get; set; }

        public string Encargado { get; set; }

        public double Temp_1 { get; set; }

        public double Temp_2 { get; set; }

    }
}

