//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Secado : Evento
{
    public Secado()
    {
    }

    public Secado(Motivos_Secado motivosSecado)
    {
        Motivos_secado = motivosSecado;
    }

    public virtual Motivos_Secado Motivos_secado { get; set; }

}

