//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Secado : Evento
    {
        public Secado()
        {
            Nombre = "Secado";
        }

        public Secado(Motivos_Secado motivosSecado)
        {
            Motivos_secado = motivosSecado;
        }

        public Secado(Motivos_Secado motivosSecado, Enfermedades enfermedad)
        {
            Motivos_secado = motivosSecado;
            Enfermedad = enfermedad;
        }

        public virtual Motivos_Secado Motivos_secado { get; set; }

        public Enfermedades Enfermedad { get; set; }

        public override string ToString()
        {
            string str = "";
            if (Motivos_secado == Motivos_Secado.RAZONES_SANITARIAS) 
                str = " " + Enfermedad;
            return "Motivo del secado: " + Motivos_secado.ToString() + str;
        }

    }
}

