//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Secado : Evento
    {
        public Secado()
        {
            Nombre = "Secado";
        }

        public Secado(short motivosSecado)
        {
            IdMotivoSecado = motivosSecado;
        }

        public Secado(short motivosSecado, short enfermedad)
        {
            IdMotivoSecado = motivosSecado;
            Enfermedad = enfermedad;
        }

        public virtual short IdMotivoSecado { get; set; }

        //public Motivos_Secado Motivo { get; set; }

        public string MotivoSecado { get; set; }

        public short? Enfermedad { get; set; }

        public string EnfermedadNombre { get; set; }

        public string LiquidacionLact { get; set; }

   
        public override string ToString()
        {
            string strLiqLact = "";
            string strEnf = "";
            string motivoStr = "";

            if (IdMotivoSecado == 2 && EnfermedadNombre != "")
                strEnf = " (" + EnfermedadNombre + ")";

            if (LiquidacionLact != "")
            {
                strLiqLact = " - " + LiquidacionLact;
            }

            switch (IdMotivoSecado)
            {
                case 1:
                    motivoStr = "LACTANCIA COMPLETA";
                    break;
                case 2: 
                    motivoStr = "RAZONES SANITARIAS";
                    break;
                case 3:
                    motivoStr = "BAJA PRODUCCION";
                    break;
                case 4: 
                    motivoStr = "PREÑEZ AVANZADA";
                    break;
            }

            return "Motivo del secado: " + motivoStr + strEnf + strLiqLact;
        }

    }
}

