//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Servicio : Evento
    {
        public Servicio()
        {
            Nombre = "Servicio";
        }

        public Servicio(char servMontaNatural, string regPadre, Empleado inseminador)
        {
            Serv_monta_natural = servMontaNatural;
            Reg_padre = regPadre;
            Inseminador = inseminador;
        }

        public char Serv_monta_natural { get; set; }

        public string Reg_padre { get; set; }

        public Empleado Inseminador { get; set; }

        public override string ToString()
        {
            string insm = "";
            if (Inseminador != null) insm = ". Inseminador: " + Inseminador.ToString();
            return "Registro padre: " + Reg_padre + ". Monta natural: " + Serv_monta_natural.ToString() + insm;
        }
    }
}

