//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Servicio : Evento
    {
        public Servicio()
        {
        }

        public Servicio(bool servMontaNatural, Animal regPadre, Empleado inseminador, Animal animal, Empleado empleado)
        {
            Serv_monta_natural = servMontaNatural;
            Reg_padre = regPadre;
            Inseminador = inseminador;
            Animal = animal;
            Empleado = empleado;
        }

        public bool Serv_monta_natural { get; set; }

        public Animal Reg_padre { get; set; }

        public Empleado Inseminador { get; set; }

        public virtual Animal Animal { get; set; }

        public virtual Empleado Empleado { get; set; }

    }
}

