//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Usuario
    {
        public Usuario()
        {
        }

        public Usuario( string nickname, string password, string nombre, string apellido, 
                        string email, string foto, string rol, bool habilitado)
        {
            Nickname = nickname;
            Password = password;
            Nombre = nombre;
            Apellido = apellido;
            Email = email;
            Foto = foto;
            Rol = rol;
            Habilitado = habilitado;
        }

        public string Nickname { get; set; }

        public string Password { get; set; }

        public string Nombre { get; set; }

        public string Apellido { get; set; }

        public string Email {  get; set; }

        public string Rol { get; set; }

        public string Foto { get; set; }

        public bool Habilitado { get; set; }

        public override string ToString()
        {
            return Nombre + " " + Apellido + " (" + Nickname + ")";
        }

    }
}

