//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    public class Venta : Evento
    {
        public Venta()
        {
            Nombre = "Venta";
        }

        public override string ToString()
        {
            return Comentarios;
        }

    }
}

